language: node_js
node_js:
 - "4.4.2"
script: "npm run-script test-travis"
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
